"""wiki_search_indices

Revision ID: 4f57ada35f08
Revises: cccf0cf64943
Create Date: 2026-09-07 15:07:07.344923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f57ada35f08'
down_revision = 'cccf0cf64943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biography_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biography_records_author_username'), ['author_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_biography_records_record_type'), ['record_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_biography_records_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biography_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biography_records_status'))
        batch_op.drop_index(batch_op.f('ix_biography_records_record_type'))
        batch_op.drop_index(batch_op.f('ix_biography_records_author_username'))

    # ### end Alembic commands ###
