"""related_organization_id

Revision ID: cccf0cf64943
Revises: 0007_attachment_media
Create Date: 2026-08-12 14:25:54.633407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cccf0cf64943'
down_revision = '0007_attachment_media'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biography_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_biography_records_related_organization_id'), ['related_organization_id'], unique=False)

    with op.batch_alter_table('device_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('device_sessions_token_hash_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_device_sessions_token_hash'))
        batch_op.create_index(batch_op.f('ix_device_sessions_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_sessions_token_hash'))
        batch_op.create_index(batch_op.f('ix_device_sessions_token_hash'), ['token_hash'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('device_sessions_token_hash_key'), ['token_hash'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('biography_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biography_records_related_organization_id'))
        batch_op.drop_column('related_organization_id')

    # ### end Alembic commands ###
